const EN = {
  title: "Palza Market",
  home: "home",
  settings: "Settings",
  config: "Configuration",
  dashboard: "Dashboard",
  about: "About",
  realstateSearch: "매물 검색",
  realstateSales: "거래 완료매물",
  realstateHub: "창업 허브",
  community: "커뮤니티",
  categories: "Categories",
  profile: "Profile",
  wishlist: "Wishlist",
  realstates: "Realstates",
  reviews: "Reviews",
  notices: "Notices",
  reports: "Reports",
  homePage: "Home Page",
  users: "Users",
  crontab: "Crontab",
  banners: "Banners",
  signIn: "Sign In",
  signUp: "Sign Up",
  signOut: "Sign Out",
  email: "E-mail",
  password: "Password",
  kakao: "Kakaotalk",
  google: "Google",
  naver: "Naver",
  signUpIndividual: "일반 회원가입",
  signUpAgency: "중개사무소 회원가입",
  username: "Username",
  verifyUser: "본인 실명확인",
  name: "Name",
  phoneNo: "Phone No.",
  confirmPassword: "Confirm Password",
  termsAndConditions: "약관동의",
  consent: "개인정보수집 및 이용에 대한 동의",
  must: "필수",
  managerPhoneNo: "대표전화번호",
  businessRegistrationNo: "사업자등록번호",
  businessLicense: "사업자등록증",
  brokerageRegistrationCard: "중개사무소등록증",
  viewTermsAndConditions: "약관보기",
  findAgency: "중개사무소 찾기",
  startFindingAgency: "조회하기",
  searchBusinessName: "사업자 상호명으로 검색가능",
  confirm: "확인",
  businessName: "사업자 상호",
  businessRepresentative: "사업자 대표명",
  brokerageRecordNo: "중개들록번호",
  legalAddress: "지번 주소지",
  magazine: "Magazine",
  franchise: "Franchise",
  agencyLanding: "중개사무소 가입 \n및 광고문의",
  smsMessages: "SMS Messages",
  agencySettings: "Agency Settings",
  displayName: "Display Name",
  edit: "Edit"
}
//
export default EN
