const EN = {
  title: "Title",
  home: "메인화면",
  settings: "설정",
  config: "Configuration",
  dashboard: "마이페이지",
  about: "About",
  realstateSearch: "매물 검색",
  realstateSales: "거래 완료매물",
  realstateHub: "창업 허브",
  community: "커뮤니티",
  categories: "카테고리",
  profile: "프로필",
  wishlist: "내가 찜한 목록",
  realstates: "매물",
  reviews: "계약후기",
  notices: "공지사항",
  reports: "허위 매물 신고",
  homePage: "홈페이지",
  users: "유저",
  crontabs: "Crontabs",
  banners: "배너",
  signIn: "로그인",
  signUp: "회원가입",
  signOut: "로그아웃",
  email: "이메일",
  password: "비밀번호",
  kakao: "카카오톡",
  google: "구글",
  naver: "네이버",
  signUpIndividual: "일반 회원가입",
  signUpAgency: "중개사무소 회원가입",
  username: "사용자 이름",
  verifyUser: "본인 실명확인",
  name: "이름",
  phoneNo: "휴대폰 번호",
  confirmPassword: "비밀번호 확인",
  termsAndConditions: "약관동의",
  consent: "개인정보수집 및 이용에 대한 동의",
  must: "필수",
  managerPhoneNo: "대표 전화번호",
  businessRegistrationNo: "사업자등록번호",
  businessLicense: "사업자등록증",
  brokerageRegistrationCard: "중개사무소등록증",
  viewTermsAndConditions: "약관보기",
  findAgency: "중개사무소 찾기",
  startFindingAgency: "조회하기",
  searchBusinessName: "사업자 상호명으로 검색가능",
  confirm: "확인",
  businessName: "사업자 상호",
  businessRepresentative: "사업자 대표명",
  brokerageRecordNo: "중개등록번호",
  legalAddress: "지번 주소지",
  magazines: "팔자 매거진",
  franchises: "프랜차이즈 창업",
  agencyLanding: "중개사무소 \n가입안내",
  smsMessages: "문자메세지 전송",
  agencySettings: "에이전시 설정",
  displayName: "Display Name",
  edit: "수정",
  save: "Save",
  general: "General",
  APIKeys: "API Keys",
  description: "Description",
  faxNo: "Fax No.",
  kakaoKey: "Kakao Key",
  googleKey: "Google Key",
  naverKey: "Naver Key",
  gambiaKey: "Gabia Key",
  nsdiKey: "NSDI Key",
  odcloudKey: "Odcloud Key",
  pending: "Pending...",
  info: "Info",
  changePassword: "Change Password",
  currentPassword: "Current Password",
  newPassword: "New Password",
  confirmNewPassword: "Confirm New Password",
  cancel: "Cancel",
  create: "Create",
  category: "Category",
  createdAt: "Created At",
  updatedAt: "Updated At",
  noDataAvailable: "No Data Available.",
  createNotice: "Create Notice",
  content: "Content",
  thumbnail: "Thumbnail",
  actions: "Actions",
  label: "Label",
  update: "update",
  externalUrl: "External Url",
  storeCount: "Store Count",
  monthlySales: "Monthly Sales",
  startingCost: "Starting Cost",
  createFranchise: "Create Franchise",
  newsSource: "News Source",
  viewCount: "View Count",
  status: "Status",
  progress: "Progress",
  refresh: "Refresh",
  sendSMS: "Send SMS Message",
  send: "Send",
  recieverPhoneNo: "Reciever Phone No.",
  realstateId: "Realstate ID",
  userId: "User ID"
}
//
const Lang = ((lang) => {
  return lang
})(EN)
//
export default Lang
