const EN = {
  title: "제목",
  home: "메인화면",
  settings: "설정",
  config: "관리자",
  dashboard: "마이페이지",
  about: "About",
  realstateSearch: "매물 검색",
  realstateSales: "거래 완료매물",
  realstateHub: "창업 허브",
  community: "커뮤니티",
  categories: "카테고리",
  profile: "회원정보",
  wishlist: "내가 찜한 목록",
  realstates: "매물",
  reviews: "계약후기",
  notices: "공지사항",
  reports: "허위 매물 신고",
  homePage: "홈페이지",
  users: "유저",
  crontabs: "Crontabs",
  banners: "배너",
  signIn: "로그인",
  signUp: "회원가입",
  signOut: "로그아웃",
  email: "이메일",
  password: "비밀번호",
  kakao: "카카오톡",
  google: "구글",
  naver: "네이버",
  signUpIndividual: "일반 회원가입",
  signUpAgency: "중개사무소 회원가입",
  username: "사용자 이름",
  verifyUser: "본인 실명확인",
  name: "이름",
  phoneNo: "휴대폰 번호",
  confirmPassword: "비밀번호 확인",
  termsAndConditions: "약관동의",
  consent: "개인정보수집 및 이용에 대한 동의",
  must: "필수",
  managerPhoneNo: "대표 전화번호",
  businessRegistrationNo: "사업자등록번호",
  businessLicense: "사업자등록증",
  brokerageRegistrationCard: "중개사무소등록증",
  viewTermsAndConditions: "약관보기",
  findAgency: "중개사무소 찾기",
  startFindingAgency: "조회하기",
  searchBusinessName: "사업자 상호명으로 검색가능",
  confirm: "확인",
  businessName: "사업자 상호",
  businessRepresentative: "사업자 대표명",
  brokerageRecordNo: "중개등록번호",
  legalAddress: "지번 주소지",
  magazines: "팔자 매거진",
  franchises: "프랜차이즈 창업",
  agencyLanding: "중개사무소 \n가입안내",
  smsMessages: "문자메세지 전송",
  agencySettings: "에이전시 설정",
  displayName: "닉네임",
  edit: "수정",
  save: "저장",
  general: "General",
  APIKeys: "API 키",
  description: "설명",
  faxNo: "Fax 번호",
  kakaoKey: "Kakao Key",
  googleKey: "Google Key",
  naverKey: "Naver Key",
  gambiaKey: "Gabia Key",
  nsdiKey: "NSDI Key",
  odcloudKey: "Odcloud Key",
  pending: "보류중...",
  info: "정보수정",
  changePassword: "비밀번호 변경",
  currentPassword: "현재 비밀번호",
  newPassword: "새 비밀번호",
  confirmNewPassword: "새 비밀번호 확인",
  cancel: "취소하기",
  create: "후기 작성하기",
  category: "카테고리",
  createdAt: "Created At",
  updatedAt: "Updated At",
  noDataAvailable: "자료 없음.",
  createNotice: "공지사항 작성하기",
  content: "내용",
  thumbnail: "메인 이미지",
  actions: "처리상태",
  label: "업종",
  update: "업데이트",
  externalUrl: "외부 링크",
  storeCount: "매장 수",
  monthlySales: "월 매출",
  startingCost: "창업비용",
  createFranchise: "Create Franchise",
  newsSource: "출처",
  viewCount: "조회수",
  status: "Status",
  progress: "Progress",
  refresh: "새로고침",
  sendSMS: "메세지 보내기",
  send: "등록하기",
  recieverPhoneNo: "받는 사람 전화번호",
  realstateId: "Realstate ID",
  userId: "아이디",
  userIdSave: "아이디 저장",
  myReviews: "내가 쓴 후기",
  myReports: "신고 상태",
  rating: "평점",
  agencyId: "Agency ID",
  myWishlist: "내가 찜한 매물",
  myRealstates: "My Realstates",
  requests: "의뢰",
  purchaseSaleRequest: "매수/매도 의뢰",
  total: "전체",
  articles: "건",
  search: "검색",
  more: "더보기",
  close: "닫기",
  go: "Go",
  customerRelation: "고객상담",
  serviceGuide: "이용안내",
  previous: "이전",
  next: "다음",
  purchaseType: "의뢰 종류",
  sale: "매수 의뢰",
  buy: "매도 의뢰",
  saleReview: "매수 후기",
  buyReview: "매도 후기",
  franchisesIntro: "프랜차이즈 창업 안내"
}
//
const Lang = ((lang) => {
  return lang
})(EN)
//
export default Lang

