name: deploy
on:
  push:
    branches: [ "designs" ]

jobs:
  deploy:
    name: (Dev) Deployment
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials (Vplate)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Sync React App to S3
        run: |
          aws s3 sync "./" "s3://palza-market-designs/" --cache-control max-age=0,public